image: node:latest

stages:
  -build-test

job 0:
  stage: .pre
  script: echo 'tests beginning'

job 1:
  stage : build-test
  script:
  -npm install
  - node server.js &
  -npm test "test/static/clientTest.js
  -npm test "test/static/gameTest.js
  -npm test "test/static/matchmakeTest.js